name: Build iOS IPA

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Enable iOS
        run: flutter config --enable-ios

      - name: Build IPA unsigned
        run: flutter build ipa --no-codesign

      - name: Upload IPA
        uses: actions/upload-artifact@v6
        with:
          name: ios-app
          path: build/ios/ipa/Runner.ipa